# temporary file to store seats data:

all_seats = [
    {'row': 1, 'number': 1, 'available': False},
    {'row': 1, 'number': 2, 'available': False},
    {'row': 1, 'number': 3, 'available': True},
    {'row': 1, 'number': 4, 'available': True},
    {'row': 1, 'number': 5, 'available': True},
    {'row': 1, 'number': 6, 'available': True},
    {'row': 1, 'number': 7, 'available': True},
    {'row': 1, 'number': 8, 'available': True},
    {'row': 2, 'number': 1, 'available': True},
    {'row': 2, 'number': 2, 'available': True},
    {'row': 2, 'number': 3, 'available': True},
    {'row': 2, 'number': 4, 'available': True},
    {'row': 2, 'number': 5, 'available': False},
    {'row': 2, 'number': 6, 'available': True},
    {'row': 2, 'number': 7, 'available': True},
    {'row': 2, 'number': 8, 'available': False},
    {'row': 3, 'number': 1, 'available': True},
    {'row': 3, 'number': 2, 'available': True},
    {'row': 3, 'number': 3, 'available': True},
    {'row': 3, 'number': 4, 'available': True},
    {'row': 3, 'number': 5, 'available': True},
    {'row': 3, 'number': 6, 'available': True},
    {'row': 3, 'number': 7, 'available': True},
    {'row': 3, 'number': 8, 'available': True},
    {'row': 4, 'number': 1, 'available': True},
    {'row': 4, 'number': 2, 'available': True},
    {'row': 4, 'number': 3, 'available': True},
    {'row': 4, 'number': 4, 'available': True},
    {'row': 4, 'number': 5, 'available': True},
    {'row': 4, 'number': 6, 'available': True},
    {'row': 4, 'number': 7, 'available': True},
    {'row': 4, 'number': 8, 'available': True},
    {'row': 5, 'number': 1, 'available': True},
    {'row': 5, 'number': 2, 'available': True},
    {'row': 5, 'number': 3, 'available': True},
    {'row': 5, 'number': 4, 'available': True},
    {'row': 5, 'number': 5, 'available': True},
    {'row': 5, 'number': 6, 'available': True},
    {'row': 5, 'number': 7, 'available': True},
    {'row': 5, 'number': 8, 'available': True},
]
